# Site settings
title: Lorenzoli's castle
email: lilesmth@gmail.com
description: "请安顿好马匹，随我入城"
baseurl: ""
url: "http://ifgladlee.github.com"
#twitter_username: ifgladlee
github_username:  ifgladlee

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               class