# Site settings
title: 梦剑行者的城堡
email: lilesmth@gmail.com
description: "这里是梦剑行者的城堡，请安顿好马匹，随我入城"
baseurl: ""
url: "http://ifgladlee.github.com"
twitter_username: ifgladlee
github_username:  ifgladlee

# Build settings
markdown: kramdown
permalink: pretty
